<?xml version="1.0" encoding="UTF-8"?>
<!--Created by TIBCO WSDL-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bvc.com.co/Services/Service0107" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns="http://www.bvc.com.co/BUS" xmlns:ns1="http://www.fixprotocol.org/FIXML-5-0" name="Untitled" targetNamespace="http://www.bvc.com.co/Services/Service0107">
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bvc.com.co/BUS" elementFormDefault="qualified" attributeFormDefault="unqualified">
			<xs:include schemaLocation="FirmInfo.xsd"/>
		</xs:schema>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.fixprotocol.org/FIXML-5-0" elementFormDefault="qualified" attributeFormDefault="unqualified">
			<xs:include schemaLocation="fixml-securitystatus-impl-5-0.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="firm">
		<wsdl:part name="parameters1" element="ns:firm"/>
	</wsdl:message>
	<wsdl:message name="SecDef">
		<wsdl:part name="parameters2" element="ns1:SecDef"/>
	</wsdl:message>
	<wsdl:portType name="portType">
		<wsdl:operation name="NotificacionEspeciesRqstOp">
			<wsdl:input message="tns:firm"/>
			<wsdl:output message="tns:SecDef"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="portTypeEndpointBinding" type="tns:portType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="NotificacionEspeciesRqstOp">
			<soap:operation soapAction="/Services/Service0107/Interface/Service0107.serviceagent/portTypeEndpoint/NotificacionEspeciesRqstOp" style="document"/>
			<wsdl:input>
				<soap:body parts="parameters1" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="parameters2" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Service0107">
		<wsdl:port name="portTypeEndpoint" binding="tns:portTypeEndpointBinding">
			<soap:address location="https://busintegracion.bvc.com.co:443/Services/Service0107/Interface/Service0107.serviceagent/portTypeEndpoint"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
